#!/usr/bin/env python

import argparse
import logging
import os

from fuse import FUSE 

from genbankfs import GenbankSearch, GenbankCache, GenbankFuse

if __name__ == '__main__':
  default_cache_dir = os.path.join(os.path.expanduser('~'), '.genbankfs')

  parser = argparse.ArgumentParser()
  parser.add_argument("assembly_details", type=argparse.FileType('r'))
  parser.add_argument("mount_point", type=str)
  parser.add_argument("--cache", type=str, default=default_cache_dir)
  args = parser.parse_args()

  logging.basicConfig(level=logging.INFO)

  searcher = GenbankSearch(args.assembly_details)
  url_lookup_function = searcher.build_url_lookup()
  cache = GenbankCache(args.cache, url_lookup_function)
  fuse = FUSE(GenbankFuse(searcher, cache), args.mount_point, foreground=True)
