#!/usr/bin/env python

import argparse
import logging

from fuse import FUSE 

from genbankfs import GenbankSearch, GenbankCache, GenbankFuse

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument("assembly_details", type=argparse.FileType('r'))
  parser.add_argument("mount_point", type=str)
  args = parser.parse_args()

  logging.basicConfig(level=logging.DEBUG)

  searcher = GenbankSearch(args.assembly_details)
  fuse = FUSE(GenbankFuse(searcher), args.mount_point, foreground=True)
